### ISSUE TITLE
Can't evaluate `.#generate-k8s`: `invalid regular expression`

### ISSUE THREAD

**Issue by felixscheinost** [hall/kubenix#15]
Hi, 

I just tried a `nix build .#generate-k8s` which fails with a Nix evaluation error:

```
error: invalid regular expression '(  |)+'

       at /nix/store/255f8yvapjp479bi5h3ngyqsrc25qh94-source/jobs/generators/k8s/default.nix:24:64:

           23|
           24|     removeEmptyLines = str: concatStringsSep "\n" (filter (l: (builtins.match "(  |)+" l) == null) (splitString "\n" str));
```

I am using Nix 2.11.1. 

 The regex `(  |)+` in principle seems correct to me but shouldn't `builtins.match "\s*" l  !+ null` be a simpler way to test whether a line is "empty" (which I assume means blank, zero characters or only space characters). Or is there some edge case I am missing?

**Comment by hall** [comment]
Thanks for opening this issue. I probably should have done so when it was first mentioned in https://github.com/hall/kubenix/issues/12#issuecomment-1405512084.

I'm guessing you're also on darwin. Your proposed changed looks similar to [mine a few comments down](https://github.com/hall/kubenix/issues/12#issuecomment-1407464282). Though I don't really have a way to test on darwin to ensure it actually works (if it results in no diff for the generated modules, it's likely a suitable fix).

However, I just did a quick test on my end (`x86_64-linux`) and `\s*` appears to delete several non-empty lines.

**Comment by felixscheinost** [comment]
Yeah, didn't test when opening the issue.

I tested with the fix you proposed (`(l: builtins.match "[[:space:]]*" l != [])`) by doing `rm modules/generated/* && nix run .#generate` and it seems like all files are generated exactly the same as before!

**Comment by hall** [comment]
Great! Merged the fix you submitted.

fwiw, [`nix run '.#generate'` will do the `rm` automatically](https://github.com/hall/kubenix/blob/5bcab30ed204bfbf8ff6a37e67af154ff8aac16e/flake.nix#L130)
