### ISSUE TITLE
Example Deployment in docs does not work

### ISSUE THREAD

**Issue by elmarsto** [hall/kubenix#28]
The example shown at 
https://kubenix.org/examples/deployment/

Is currently broken. The pods fail with the complaint about the 'daemon' directive being duplicated. I speculate that the default nginx config has changed. 

The example at https://kubenix.org/examples/deployment/ works if you remove the line that reads  `        daemon off;` from `module.nix`

**Comment by elmarsto** [comment]
But I daresay I love this project, so while I have you on the line: thank you!

**Comment by hall** [comment]
Well now everyone knows that I didn't test whether the examples actually run :sweat_smile:

Thanks for submitting this issue :100: I've pushed [a commit with your fix](https://github.com/hall/kubenix/commit/60a5a28db7ab569ccfd342caadd44824b64c7c93).
