### ISSUE TITLE
Search box in docs not working

### ISSUE THREAD

**Issue by yajo** [hall/kubenix#41]
Using Firefox 119.0 (64-bit) here.

The search box doesn't work.

**Comment by hall** [comment]
Thanks for reporting :100: it's been a while so I've just [bumped the theme](https://github.com/hall/kubenix/commit/e4d036576436b9983216584a89388af3da995043) and search appears to be working (again?). Can't say whether this has broken anything else though :grin: definitely open another issue if you find more bugs!
