### ISSUE TITLE
Talk for NixCon Berlin

### ISSUE THREAD

**Issue by pizzapim** [hall/kubenix#71]
Not sure if there is a better channel for this, but I am thinking of giving a talk at [NixCon Berlin](https://2024.nixcon.org/) about Kubenix and how I use it in my homelab. Mainly to spread some awareness because I like this project :) 

Some things I am thinking of presenting:
- How the k8s resource definitions are generated from the swagger API
- How Helm charts are handled
- How I am using it personally in my homelab
- Maybe a small demo? :)

I am not intimately familiar with the inner workings of the code base so it will be a researching exercise for me as well. Any ideas, help or suggestions are appreciated!

**Comment by adrian-gierakowski** [comment]
@pizzapim I’ve read all of the code and have decent understanding of how it works under the hood. Would be happy to help with this as I think it would be beneficial for the project and the wider community. Could even do a screen sharing session at some point if needed.

**Comment by pizzapim** [comment]
@adrian-gierakowski That would be awesome! I'm still contemplating whether this should be a lightning talk or a longer one. In case of a longer one, we should be careful it does not have too much overlap with this awesome talk from last year: https://www.youtube.com/watch?v=SEA1Qm8K4gY

**Comment by pizzapim** [comment]
My proposal got accepted! I think I'll have a first draft for a presentation sometime this week. @adrian-gierakowski If you are still up for it, maybe you'd like to give some early feedback on it? Do you have a Matrix account I can contact you on?

**Comment by pizzapim** [comment]
Oops, didn't update this thread yet. There was quite a bit of interest, also after the presentation. So I consider the talk to be a success :)
