### ISSUE TITLE
fully qualify objects

### ISSUE THREAD

**Issue by hall** [hall/kubenix#8]
As it stands, objects do not need to specify a namespace which makes creating resources with the same name but in different namespaces a bit awkward. Since config keys cannot clash, the `metadata.name` must be explicitly set and the duplicate config name (i.e., `example2` here) is now something arbitrary and ignored, e.g.,

```nix
{
  kubernetes.resources.pods = {
    example.metadata.namespace = "default";
    example2.metadata = {
      name = "example";
      namespace = "other";
    };
  };
}
```

Whereas we could treat an object's namespace in the same way we treat its name and it becomes something like:

```nix
{
  kubernetes.namespaces = {
    default.resources.pods.example = {};
    other.resources.pods.example = {};
  };
}
```

The new `namespaces` key is useful (as opposed to just `kubernetes.${namespace}`) to prevent clashing with a namespace named `resources` or `helm`, for example. And non-namespaced resources can remain defined in the old `kubernetes.resources` location.

```nix
{
  kubernetes = {
    namespaces.default.resources.pods.example = {};
    resources.persistentvolumes.example = {};
  };
}
```

Along these lines, it might also be useful to create a context key in order to move toward multi-cluster deployments.

```nix
{
  kubernetes.${context}.namespaces.${namespace}.resources = {};
}
```

So the full config, with unambiguous namespace and context, becomes:

```nix
{
  kubernetes.my-cluster = {
    kubeconfig = "/path/to/kubeconfig";
    namespaces.default.resources = {}; # namespaced
    resources = {};                    # non-namespaced
  };
}
```

This is a bit more verbose but I think it might be decent a step towards deterministic executions as it no longer relies on the user's environment to determine the current context/namespace (obviously we're still pulling arbitrary kubeconfig files as string values but those contain sensitive data so should be handled with a proper nix secrets manager).

**Comment by adrian-gierakowski** [comment]
How about using kubenix submodule for grouping resources into different namespaces? You should be able to set a default namespace per submodule instance. I can create an example of how to do this tomorrow.

**Comment by hall** [comment]
Yeah, that could work! Still learning the ins and outs of (sub-)modules so would definitely appreciate an example :+1:

**Comment by matejc** [comment]
I think the code is here, not just that you can set the namespace per module, apparently you can also set k8s version. https://github.com/hall/kubenix/blob/main/modules/k8s.nix#L439

**Comment by hall** [comment]
Thanks @matejc! For some reason I'd missed your comment here.

Will take a look at your config (along with the docs MR Adrian submitted) and give it a go. I'll leave this issue open for now but will close it if I don't run into any trouble.
